# Generated by Django 4.1.1 on 2022-10-26 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Code number of the course')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name of the course')),
                ('type', models.CharField(max_length=30, verbose_name='Type of the course')),
                ('number_of_days', models.IntegerField(verbose_name='Number of days of the course')),
                ('number_of_students', models.IntegerField(verbose_name='Number of students of the course')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Code number of the organization')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name of the organization')),
                ('address', models.CharField(max_length=50, verbose_name='Address of the organization')),
                ('telephone', models.CharField(max_length=30, verbose_name='Telephone of the organization')),
                ('email', models.EmailField(max_length=40, verbose_name='Email of the organization')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_staff', models.IntegerField(verbose_name='Number of staff')),
                ('start_date', models.DateField(verbose_name='Start date of the course')),
                ('end_date', models.DateField(verbose_name='End date of the course')),
                ('name_of_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course', verbose_name='Name of course')),
                ('name_of_requesting_organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.organization', verbose_name='Name of the requesting organization')),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Code number of teacher')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full name of teacher')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('sex', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=10, verbose_name='Sex')),
                ('education', models.TextField(verbose_name='Education')),
                ('category', models.CharField(choices=[('Higher', 'Higher'), ('First', 'First'), ('Second', 'Second')], max_length=10, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full name of employee')),
                ('post', models.CharField(max_length=100, verbose_name='Post of employee')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.request', verbose_name='Name of request')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='DocumentTeacherCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.request', verbose_name='Number of Request')),
                ('name_of_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course', verbose_name='Name of course')),
                ('name_of_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.teacher', verbose_name='Name of teacher')),
            ],
            options={
                'verbose_name': 'Document with relation of teacher and course',
                'verbose_name_plural': 'Documents with relations of teachers and courses',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPriceCourse',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Code number of document')),
                ('date', models.DateField(verbose_name='Date of establishment')),
                ('price', models.IntegerField(verbose_name='Established price')),
                ('final_price', models.IntegerField(default=0, verbose_name='Final price of the course')),
                ('name_of_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course', verbose_name='Name of the course')),
            ],
            options={
                'verbose_name': 'Document with new price',
                'verbose_name_plural': 'Documents with new prices',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='name_of_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.organization', verbose_name='Name of the parent organization'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.documentpricecourse', verbose_name='Price of the course'),
        ),
    ]
